import {
  CREATE_CONTACT_QUERY,
  DELETE_CONTACT_QUERY,
  GET_CONTACT_QUERY,
  GET_CONTACT_DETAIL_QUERY,
  UPDATE_CONTACT_QUERY,
  UPDATE_PHONE_NUMBER_CONTACT_QUERY,
  ADD_NUMBER_TO_CONTACT,
} from "./contact";

export {
  GET_CONTACT_QUERY,
  CREATE_CONTACT_QUERY,
  DELETE_CONTACT_QUERY,
  GET_CONTACT_DETAIL_QUERY,
  UPDATE_CONTACT_QUERY,
  UPDATE_PHONE_NUMBER_CONTACT_QUERY,
  ADD_NUMBER_TO_CONTACT,
};
