const GET_CONTACT = "GET_CONTACT";
const CREATE_CONTACT = "CREATE_CONTACT";
const DELETE_CONTACT = "DELETE_CONTACT";

export default Object.freeze({ GET_CONTACT, CREATE_CONTACT, DELETE_CONTACT });
export { GET_CONTACT, CREATE_CONTACT, DELETE_CONTACT };
